services:
  - type: web
    name: portfolio-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py create_admin
      python manage.py collectstatic --noinput
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: portfolio-app.onrender.com
