# Generated by Django 5.1.4 on 2025-06-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_info"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Info",
        ),
    ]
