# Generated by Django 5.1.4 on 2025-06-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0004_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="skills_ai",
            new_name="skills",
        ),
        migrations.RenameField(
            model_name="info",
            old_name="skills_db",
            new_name="work_experience",
        ),
        migrations.RemoveField(
            model_name="info",
            name="skills_embedded",
        ),
        migrations.RemoveField(
            model_name="info",
            name="skills_programming",
        ),
        migrations.RemoveField(
            model_name="info",
            name="skills_vc",
        ),
        migrations.RemoveField(
            model_name="info",
            name="skills_web",
        ),
        migrations.RemoveField(
            model_name="info",
            name="work_description",
        ),
        migrations.RemoveField(
            model_name="info",
            name="work_period",
        ),
        migrations.RemoveField(
            model_name="info",
            name="work_title",
        ),
        migrations.AlterField(
            model_name="info",
            name="subtitle",
            field=models.CharField(max_length=200),
        ),
    ]
